version : "3.7"

services:
  slave:
    build: .
    container_name: jenkins_slave
    volumes:
      - /data/jenkins_agent:/home/jenkis/agent
      - /data/jenkins_agent:/home/jenkis/.jenkins
    ports:
      - 8888:8888
    restart: unless-stopped